### ISSUE TITLE
Programmer tutorial

### ISSUE THREAD

**Issue by hroest** [OpenMS/Tutorials#96]
I think it would be nice if there were a tutorial for people who want  to use OpenMS scripting and on the command line. Right now there are nice tutorials on how to use OpenMS using KNIME  but if I want to deploy OpenMS on a cluster or learn how the individual tools work on the commandline, there is no tutorial. What about having a tutorial track that is more oriented towards the CLI, this may also help us to get new programmers.

**Comment by timosachsenberg** [comment]
Hi Hannes. We basically might have two sources.
The developer manual for programmers (currently WIP) that I will send you as link.
The TOPP tutorial in OpenMS (which is generated from the source tree: https://github.com/OpenMS/Tutorials/blob/master/Handout/TOPP_tutorial.pdf)

**Comment by NebuchadnezzaraHardrada** [comment]
@timosachsenberg The link you provided only shows how one can use TOPPAS and TOPPView. I have to admit that I am not a programmer and so am a little bit ignorant when it comes to such issues. Having gone through the tutorial, there is no mention at all on how one can use the command line to run OpenMS.Should the console be pointed to the OpenMS installation directory or to the python installation ? Every time I run some examples (e.g creating an -ini parameter file, I always encounter problems related to syntax). Do I need to make python scripts that import OpenMS modules and then run those scripts on command line ?How can one use OpenMS Simulator ?

**Comment by timosachsenberg** [comment]
Hi. On what operating system are you working on?
OpenMS consists of many small tools (the so-called TOPP tools) that you can run from the command line. (Just type the name of the tool and -help will show you its options). You can also write out an ini file by calling -write_ini FILENAME.ini that you can easily inspect using the INIFileEditor application in OpenMS.
So you don't need pyOpenMS or python if you just want to run the OpenMS tools.
But maybe we should ask what you want to achieve / build with OpenMS. Maybe we can guide you in the right direction.
Best

**Comment by NebuchadnezzaraHardrada** [comment]
I am working on a Windows 7 Professional with 64bit operating system and 40GB RAM. I have a version of OpenMS installed on my PC. I usually instead, just use KNIME workflows as they are easier to handle mentally as opposed to OpenMS TOPPAS tools. The only reason why I want to learn how to use the command line is because its the only way for me to learn how to use OpenMS Simulator and OpenSWATH. 
![openms](https://user-images.githubusercontent.com/29667095/33139955-fabf2630-cfae-11e7-9cee-0c04ba3a23b9.PNG)

The OpenSWATH tutorial has clear steps on how one can use the command line to generate spectral libraries but I have not found any source of help for TOPP. So, my question is, what should I do for me to be able to type in commands directly to the command line to simulate mass spectra from a given peptide sequence ?

**Comment by jpfeuffer** [comment]
Hi!
You can find the documentation of the MSSimulator here:
http://ftp.mi.fu-berlin.de/pub/OpenMS/release-documentation/html/UTILS_MSSimulator.html

You can Open the TOPP command line interface by typing the following in your Windows Command Prompt:
\> `"C:\Program Files\OpenMS-2.2.0\bin\command.bat"`

Then type something like:
\> `MSSimulator.exe --help`

Or any of the other parameters listed in the documentation.

**Comment by NebuchadnezzaraHardrada** [comment]
@jpfeuffer , thank you for your help. Unfortunately, I just cannot seem to wrap my head around the whole thing. I now have the console pointed to the bat file as instructed but still cannot simulate mass spectra even after reading the help section. 
![mssimulator](https://user-images.githubusercontent.com/29667095/33160228-bcd69a62-d01a-11e7-8df4-3163b0bb3316.PNG)
May you please do me the following favour  ? May you please just show me how, one can input a simple peptide together with its retention time and retrieve an output file with the simulated spectra ? Like I have said, I am not a programmer and hence the reason why I seem to be having such trivial problems.Thanks for your patience and help

**Comment by hroest** [comment]
your problem seems to be that you put each option into its own command. you need to use

```
MSSimulator -in "E:\Data\Kundai..." -out "E:\Data\Kundai..."
```

where you want to replace the path with your real examples and you *need* to put everything into one line.

**Comment by NebuchadnezzaraHardrada** [comment]
@hroest. Thank for the heads up, now I understand how to run commands.What does it mean when the program output says "Access is denied". Below is my command:

C:\Program Files\OpenMS-2.1.0\bin>-in<"E:\Data\Kundai\RawFiles\Etanercept.fasta"> -ini<C:\Users\Kundai\.TOPPAS.ini> -out<"E:\Data\Kundai\RawFiles\Output\Simulated.mzML"> -algorithm

**Access denied**

**Comment by jpfeuffer** [comment]
Can you try:

```PowerShell
MSSimulator.exe -in "E:\Data\Kundai\RawFiles\Etanercept.fasta"  -ini "C:\Users\Kundai.TOPPAS.ini"  -out "E:\Data\Kundai\RawFiles\Output\Simulated.mzML"
```
for the most basic command.

But make sure that your `C:\Users\Kundai.TOPPAS.ini` contains all required parameters from the documentation. Check out `INIFileEditor.exe` for this.

**Comment by NebuchadnezzaraHardrada** [comment]
@jpfeuffer The seems to be something wrong on my end because I tried all versions of the basic command I could come up with and none of them seem to work. For the output file, should I already give it an arbitrary name such as "Simulated.mzML" in my case or I should just point the console to the output folder where it should place the file. I have tried the following lines of code and none of them seem to work 👍 

C:\Program Files\OpenMS-2.1.0\bin> "C:\Program Files\OpenMS-2.1.0\bin\MSSimulator.exe "-in"E:\Data\Kundai\RawFiles\Etanercept.fasta"  -ini  C:\Users\Kundai.TOPPAS.ini  -out "E:\Data\Kundai\RawFiles\Output\Simulated.mzML" 

**The system cannot find file specified**

C:\Program Files\OpenMS-2.1.0\bin> -in"E:\Data\Kundai\RawFiles\Etanercept.fasta"  -ini  C:\Users\Kundai.TOPPAS.ini  -out "E:\Data\Kundai\RawFiles\Output\Simulated.mzML" 

**The syntax of the command is incorrect** 

C:\Program Files\OpenMS-2.1.0\bin> -in<"E:\Data\Kundai\RawFiles\Etanercept.fasta" > -ini  <C:\Users\Kundai.TOPPAS.ini > -out <"E:\Data\Kundai\RawFiles\Output\Simulated.mzML">

**The syntax for the command is incorrect**

C:\Program Files\OpenMS-2.1.0\bin> -in"E:\Data\Kundai\RawFiles\Etanercept.fasta"  -ini  C:\Users\Kundai.TOPPAS.ini  -out "E:\Data\Kundai\RawFiles\Output\Simulated.mzML"

**The filename, directory name or volume label syntax is incorrect.**

I do not understand my problems because I have used each and every single combinations of commands and they are all either incorrect or there is something wrong with the directory. To ensure that I do not write the file paths incorrectly, I have also been directly pasting onto the console and so as of now, I do not really understand where all the errors are coming from .

**Comment by jpfeuffer** [comment]
Hi!

You have to be careful with where to place spaces. The first command seems to be *almost* correct.
Usually there should be a space between every part of the command.
A command is built with:
```PowerShell
Executable.exe -parameter1 "Argument1" -parameter2 "Argument2" 
```
Note the space between the exe, the parameters and the arguments.
Please try to copy:
```PowerShell
"C:\Program Files\OpenMS-2.1.0\bin\MSSimulator.exe" -in "E:\Data\Kundai\RawFiles\Etanercept.fasta" -ini "C:\Users\Kundai.TOPPAS.ini" -out "E:\Data\Kundai\RawFiles\Output\Simulated.mzML"
```
And of course, make sure that the files "E:\Data\Kundai\RawFiles\Etanercept.fasta" and "C:\Users\Kundai.TOPPAS.ini" as well as the _folder_ "E:\Data\Kundai\RawFiles\Output" exist. As you guessed correctly, you should give a filename for the Simulated.mzML but it will be created for you.

**Comment by NebuchadnezzaraHardrada** [comment]
@jpfeuffer Thank you for your help, everything now works according to plan.
